ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("to_do_list.urls", namespace="to_do_list"))
]

to_do_list/urls.py
from django.urls import path, include
from .views import TagsListView, TagsDeleteView, TagsUpdateView, TagsCreateView, TaskListView, TaskDeleteView, TaskUpdateView, TaskCreateView, task_status_update

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tags/<int:pk>/delete", TagsDeleteView.as_view(), name="tags_delete"),
    path("tags/<int:pk>/update", TagsUpdateView.as_view(), name="tags-update"),
    path("tags/create", TagsCreateView.as_view(), name="tags-create"),
    path("task/<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/<operation>/", task_status_update, name="status-update"),
    path("task/create", TaskCreateView.as_view(), name="task-create")
]

app_name = "to_do_list"

to_do_list/models.py
from django.db import models
from django.forms import DateInput


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(auto_now=False, blank=True, null=True)
    is_done = models.BooleanField()
    tags = models.ManyToManyField(Tag, related_name="tasks")

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["is_done", "-datetime"]

templates/to_do_list/forms.py
from django import forms
from django.forms import ModelForm

from to_do_list.models import Task


class DateInput(forms.DateInput):
    input_type = 'date'


class TaskForm(ModelForm):

    class Meta:
        model = Task
        widgets = {
            'made_on': DateInput(),
        }
        fields = "__all__"

to_do_list/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from templates.to_do_list.forms import TaskForm
from to_do_list.models import Tag, Task


class TaskListView(generic.ListView):
    model = Task
    template_name = "to_do_list/task_list.html"
    context_object_name = "task_list"


class TagsListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"
    template_name = "to_do_list/tag_list.html"


class TagsDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("to_do_list:tags-list")


class TagsUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    template_name = "to_do_list/tag_update_form.html"
    success_url = reverse_lazy("to_do_list:tags-list")


class TagsCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("to_do_list:tags-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("to_do_list:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    template_name = "to_do_list/task_update.html"
    success_url = reverse_lazy("to_do_list:index")

class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    template_name = "to_do_list/task_create.html"
    success_url = reverse_lazy("to_do_list:index")

def task_status_update(request, pk, operation):

    task = Task.objects.get(id=pk)
    if operation == "Complete":
        task.is_done = 1
    elif operation == "Undo":
        task.is_done = 0
    task.save()
    return HttpResponseRedirect(reverse_lazy("to_do_list:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}
       </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'to_do_list:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'to_do_list:tags-list' %}">All tags</a></li>
</ul>

templates/to_do_list/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Hey, you are on the Index page.
</body>
</html>

templates/to_do_list/tag_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h1>Delete Tag</h1>
    <p>Do you really want to delete a tag?</p>
    <form action="" method="post">
    {% csrf_token %}
        <input type="submit" value="Are you sure?" class="btn btn-danger">
    </form>
{% endblock %}

templates/to_do_list/tag_form.html
{% extends "base.html" %}

{% block content %}
    <h1>Create tag</h1>
    <form action="" method="post" novalidate>
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/to_do_list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Tags List</h1>
    <a href={% url "to_do_list:tags-create"%}><input type="submit" class="btn btn-primary" value="Add" style="float: right; margin-top: -50px;"></a><br>
    {% if tag_list %}
      <table class="table">
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
        {% for tag in tag_list %}
            <tr>
              <td>
                  {{ tag.name}}
              </td>
              <td><a href={% url "to_do_list:tags_delete" pk=tag.id%}><input type="submit" class="btn btn-secondary" value="Delete"></a><br></td>
              <td><a href={% url "to_do_list:tags-update" pk=tag.id%}><input type="submit" class="btn btn-secondary" value="Update"></a></td>
          </tr>
        {% endfor %}
    {% endif %}
{% endblock %}

templates/to_do_list/tag_update_form.html
{% extends "base.html" %}

{% block content %}
    <h1>Update the tag</h1>
    <form action="" method="post" novalidate>
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/to_do_list/task_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <h1>Delete Task</h1>
    <p>Do you really want to delete a task?</p>
    <form action="" method="post">
    {% csrf_token %}
        <input type="submit" value="Are you sure?" class="btn btn-danger">
    </form>
{% endblock %}

templates/to_do_list/task_create.html
{% extends "base.html" %}

{% block content %}
    <h1>Create a task</h1>
    <form action="" method="post" novalidate>
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/to_do_list/task_list.html
{% extends "base.html" %}
{% block content %}
<h1>TODO list</h1> <button type="button" class="btn btn-primary" style="margin-left: 1180px"> <a style="color: white; " href="{% url "to_do_list:task-create" %}">Add New</a></button>
{% for task in task_list %}
    <ul>
        <span style="font-size: 30px; font-weight: 600">{{ task.content }}{% if task.is_done == 0 %} <span style="color:red">Not Done</span>{% else %}<span style="color: green"> Done</span> {% endif %}{% if task.is_done == 0%}<button type="button" class="btn btn-success" style="margin-left: 600px"> <a style="color: white; " href="{% url 'to_do_list:status-update' pk=task.id operation="Complete" %}">Complete</a></button>{% else %}<button type="button" class="btn btn-secondary" style="margin-left: 600px"> <a style="color: white; " href="{% url 'to_do_list:status-update' pk=task.id operation="Undo" %}">Undo</a></button>{% endif %}<br>
        <span style="font-size: 20px; font-weight: 400">Created: {{ task.datetime }}{% if task.deadline %} Deadline {{ task.deadline }}{% endif %}<br></span>
        <span style="font-size: 20px; font-weight: 100; color:##696969;">Tags: {% for tag in task.tags.all %}{{ tag }} {% empty %} No Tags {% endfor %}</span><span style="font-size: 20px"><a href="{% url "to_do_list:task-update" pk=task.id %} ">Update</a> <a href="{% url "to_do_list:task-delete" pk=task.id %} ">Delete</a></span><hr>
    </ul>
{% endfor %}
{% endblock %}

templates/to_do_list/task_update.html
{% extends "base.html" %}

{% block content %}
    <h1>Update the task</h1>
    <form action="" method="post" novalidate>
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Submit">
    </form>
{% endblock %}